### ISSUE TITLE
audio.cpp: wrong order when writing left/right channel

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#103]
Comment says:
/* Always put the right word before the left word.  */
and code in put_sound_word_right() just stores the sample (if mixedon) and the code in put_sound_word_left() handles the samples.
But in all sample handlers (i.e. sample16s_handler()), put_sound_word_left() is called before put_sound_word_right().
I think, correct calls are
put_sound_word_right (data2);
put_sound_word_left (data3);
instead of
put_sound_word_left (data2);
put_sound_word_right (data3);
(switch of data2 and data3 required, otherwise channels are switched).

**Comment by tonioni** [comment]
Looks like this rule was forgotten when channel ordering was fixed few years ago.. Will be fixed.

**Comment by timofonic** [comment]
Any news?

**Comment by tonioni** [comment]
Was fixed in 3.3.0b9
