### ISSUE TITLE
_wpgmptr is NULL

### ISSUE THREAD

**Issue by lab313ru** [tonioni/WinUAE#109]
WinUAE crashes because of compare with **_wpgmptr** which is null. MSDN tells that this variable is deprecated now.

**Comment by tonioni** [comment]
I couldn't duplicate this with MSVC 2015 or "15" but I replaced it with GetModuleFileName().

**Comment by timofonic** [comment]
So this is an open or closed issue? :P

**Comment by tonioni** [comment]
_wpgmptr is not used anymore.
