### ISSUE TITLE
Switch JIT and cycle-exact Chipset on/off via Hotkey/Joypad

### ISSUE THREAD

**Issue by fanattic** [tonioni/WinUAE#112]
Hi!
I would love to have a fast Workbench with the ability to switch the option JIT and cycle-exact chipset (DMA/Memopry-Accesses) AND/OR cycle-exact chipset (FULL) on and off with my Joypad while CPU Emulation speed stays at "fastest possible".
I do this manually all the time without any crashes and use it to have a fast Workbench with full WHD-LOAD compatibility. Having this option on a hotkey would be great!

cheers!

**Comment by tonioni** [comment]
For whdload recommended method is to use whdload's ExecuteStartup and ExecuteCleanup whdload.prefs parameters to run uae-configuration. For example "uae-configuration cachesize 0 m68k_speed real cycle_exact true" or similar to set back to "compatible" config and "uae-configuration cycle_exact false m68k_speed max cachesize 8192" to go back to fastest possible.

If you want shortcuts, you can use Input panel to configure similar uae-configuration on the fly config file changes by mapping key/button/whatever to "custom event". Only difference is that syntax needs commands in quotes ("cachesize 0" "m68k_speed real" "cycle_exact true").

**Comment by fanattic** [comment]
works :) thank you very much!!!!!
