### ISSUE TITLE
Bug in disk.cpp, save_disk2(...)

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#113]
The line
  dstbak = dst = xmalloc (uae_u8, 2 + 4 + 2 + 4 + 4 + size);
should be replaced by
  dstbak = dst = xmalloc (uae_u8, 4 + 2 + 4 + 2 + 4 + 4 + size + 2);
to get real size of required memory.

**Comment by timofonic** [comment]
Any news?

**Comment by tonioni** [comment]
It was fixed.
