### ISSUE TITLE
disk.cpp

### ISSUE THREAD

**Issue by ghost** [tonioni/WinUAE#12]
typedef enum { DRV_NONE = -1, DRV_35_DD = 0, DRV_35_HD, DRV_525_SD, DRV_35_DD_ESCOM } drive_type;

but in disk_creatediskfile, we check if adftype == 4 (which we don't have)
old types = /* adftype: 0=DD,1=HD,2=DD PC,3=HD PC,4=525SD */

**Comment by timofonic** [comment]
Any news?

**Comment by tonioni** [comment]
This is finally fixed.
