### ISSUE TITLE
Bug in custom.cpp, immediate_copper()

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#120]
I think, the line
	if (cop_state.ip >= currprefs.chipmem_size && cop_state.ip < currprefs.z3chipmem_start && cop_state.ip >= currprefs.z3chipmem_start + currprefs.z3chipmem_size)
			break;
should be replaced by
	if ((cop_state.ip >= currprefs.chipmem_size && cop_state.ip < currprefs.z3chipmem_start) || cop_state.ip >= currprefs.z3chipmem_start + currprefs.z3chipmem_size)
			break;
Otherwise, the result is always false and the intended check (ip inside of chipmem) wasn't done.

**Comment by tonioni** [comment]
Gah.. Unfortunately it is too late to include this in 3.5. Fixing this may trigger some last minute hidden bugs.
