### ISSUE TITLE
Handle NAN in fp_from_exten()

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#131]
For systems without long double and if SOFTFLOAT_CONVERSIONS is not an option, I would like to extend the function
fp_from_exten(...) to handle NAN:

   if(v == 0.0) {
     ...
   } else if (fp_is_nan(v)) {
     *wrd1 = 0x7fff0000;
     *wrd2 = 0xffffffff;
     *wrd3 = 0xffffffff;
     return;
   }

**Comment by tonioni** [comment]
Done.
