### ISSUE TITLE
CD32 - Changing CD and Resetting doesn't load the new CD

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#132]
I found a bug in Amiberry, which seems to exist in WinUAE as well.

### Steps to recreate:
- Change Quickstart to CD32
- Insert a CD32 game and start the emulator
- After the game is loaded and starts, enter the GUI and change the CD to another one (e.g. another game)
- Click Reset from the GUI
- Instead of rebooting and loading the other game, it reboots and shows the CD32 boot screen instead
- If you enter the GUI again, and click Reset one more time, the new game is loaded.

This seems to happen regardless of game chosen.
All settings were left at their defaults, just using Quickstart CD32 as mentioned above, to keep things simple.

**Comment by tonioni** [comment]
Fixed. When changing CDs, previous CD is removed, then very short delay starts before new CD is inserted (to simulate real world CD changing), if reset happened during the delay, new CD was never inserted.

c4fca99

**Comment by midwan** [comment]
Thanks, confirmed working! :)
