### ISSUE TITLE
Bug in lowres_set()

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#137]
https://github.com/tonioni/WinUAE/blob/fe78a1c514e6d2589355b838e02c6b7bd82c84b3/drawing.cpp#L79

Shouldn't this line be `int old = lores_shift;` instead?
Like this, the `pfield_set_linetoscr();` will never be hit since the values are always equal to each other...

**Comment by tonioni** [comment]
Yeah, it is copypaste bug. Fixed, thanks.
