### ISSUE TITLE
Possible crash at this point

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#138]
https://github.com/tonioni/WinUAE/blob/fe78a1c514e6d2589355b838e02c6b7bd82c84b3/memory.cpp#L1386

This point has caused crashes in some cases, if the Kickstart file could not be opened.

I've implemented a small fix in Amiberry as follows, to overcome that:

https://github.com/midwan/amiberry/commit/647f573a65dfd69232fd32864b49c81b23463706

It would be great if you could add this upstream (unless you have a better solution of course) so we don't have to keep fixing it with future merges :)

**Comment by tonioni** [comment]
I am not sure why it would crash (it is only called if rom image file opened successfully)
Anyway, check added:  052cc61
