### ISSUE TITLE
Bug in blkdev_cdimage.cpp, static int parsemds(...)

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#143]
The line
if (!memcmp (&head, MEDIA_DESCRIPTOR, strlen (MEDIA_DESCRIPTOR)))
should be replaced by
if (!memcmp (head, MEDIA_DESCRIPTOR, strlen (MEDIA_DESCRIPTOR)))
because head is already a pointer.

**Comment by tonioni** [comment]
Fixed.
