### ISSUE TITLE
bogus N flag set with muls.l

### ISSUE THREAD

**Issue by bebbo** [tonioni/WinUAE#150]
consider this code for 68020+:

```
    moveq #2,d0
    muls.l #-1431655765,d0
```
then the N flag must be 0 since the result is the positive value ‭`#1431655766‬` .

**Comment by tonioni** [comment]
Nice find. MULS.L and MULU.L set condition codes using full 64-bit result value (mul.l <ea>,dh:dl), even when only low 32-bit of result was returned.  I guess this has been wrong since the beginning..

**Comment by bebbo** [comment]
thanks for 3808bee0c8ba49ec16fb965b197ad1887be891f6
Now I'm waiting for 4210b6 :-)

**Comment by tonioni** [comment]
Usual alpha url was immediately updated. (Search eab for it)

**Comment by bebbo** [comment]
http://www.winuae.net/files/b/winuae.7z ?

**Comment by bebbo** [comment]
it's fixed - thank you
