### ISSUE TITLE
uaenet check for version of npcap is wrong

### ISSUE THREAD

**Issue by marcelammerlaan** [tonioni/WinUAE#151]
When running WinUAE with npcap installed the version detection reports: 

uaenet: too old npcap/winpcap, v4 or newer required

When checking, they seems to have reset the version counter from 4.x to a lower version for npcap. The current downloadable version is 0.993 for npcap.
Installing the old (unsupported winpcap) allows selection of a network device in the dropdown for "Network Mode" but RoadShow doesn't seem to be able to bring up the device (unclear if this is related to running WinPCap on WIndows 10 or some other config error on my side).

The "winpcap compat" option on npcap does not help: the check still fails.

**Comment by arm-in** [comment]
I think this is a confusion between "Npcap" and "WinPcap". Those two are doing more or less the same. WinPcap has not been maintained for years, however.

Npcap = 0.993 (from April 2019)
WinPcap = 4.1.3 (from March 2013)

See
https://nmap.org/npcap/vs-winpcap.html

**Comment by tonioni** [comment]
I added nmap.org npcap support (without need for winpcap backwards compatibility option) in 3.6.0.

It seem versioning has changed (but nothing is mentioned in changelogs?) because 0.80 (I quickly chose some older version) wpcap.dll is version 5.0.

**Comment by tonioni** [comment]
Version check removed (in next version), now only checks if all required functions exist.
