### ISSUE TITLE
Possible bug in collision detection algorithm (CLXDAT)

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#154]
Hi Toni,

I might have spotted a bug in UAE’s collision detection algorithm. The suspicious test case is 
 
    vAmigaTS/Denise/Sprites/collision5/ 

in the vAmiga test case repo at: 

    https://github.com/dirkwhoffmann/vAmigaTS

This is how my test looks like in UAE with collision detection set to „full“: 
<img width="721" alt="collision5" src="https://user-images.githubusercontent.com/12561945/62558462-61a0ea00-b879-11e9-8427-d0a1698c204d.png">

And this is how it looks like on my Amiga 500:

![IMG_1629](https://user-images.githubusercontent.com/12561945/62558412-4635df00-b879-11e9-96dc-82a704e0b35c.jpeg)

The test draws two sprites and used the vSync interrupt to transfer bit-chunks from CLXDAT to color registers 0 to 3. Hence, different bit patterns in CLXDAT cause the test image to be colorised differently.

It seems like UAE does not recognise a collision between sprite 1 and PF1 while the original Amiga does.

**Comment by tonioni** [comment]
Does it only happen if dual playfield mode is enabled? It has undocumented collision difference. I only noticed it because there was one game that depended on it. I am not sure if it is 100% correctly emulated.

btw, not related to collisions but be very careful about OCS vs ECS bitplane engine state logic because it has quite big differences (which are totally officially undocumented) in some specific situations.

**Comment by dirkwhoffmann** [comment]
I’ve added two new tests to the vAmigaTS repo: collision5s and collision5d

In contrast to the original collision5 test, the newer ones don’t toggle between single-playfield and dual-playfield mode. collision5s solely draws in single-playfield mode and collision5d solely draws in dual-playfield mode.

Both tests look different on my A500: 

collision5s: 

UAE:

<img width="721" alt="collision5s" src="https://user-images.githubusercontent.com/12561945/62626131-f9a8dd00-b926-11e9-90c0-ff277f707363.png">

Amiga 500: 

![collision5s_A500](https://user-images.githubusercontent.com/12561945/62626159-088f8f80-b927-11e9-9c70-1eb56b4b9fea.jpeg)

collision5d: 

UAE:

<img width="721" alt="collision5d" src="https://user-images.githubusercontent.com/12561945/62626114-ec8bee00-b926-11e9-9f16-887cd926f591.png">

Amiga 500: 

![collision5d_A500](https://user-images.githubusercontent.com/12561945/62626126-f1e93880-b926-11e9-855b-27d932cd4ddf.jpeg)

The first thing that should be done is to rerun the tests in UAE. I *think* that I configured it correctly (full collision detection, OCS, etc.), but I am not a frequent UAE user and there are still many options I am not 100% sure of what they relate to. The vAmigaTS repo contains ADF files for all test cases. They boot and run the test automatically. 

Side note: The collision5x tests set all MVBP bits to 0, hence triggering a collision with transparent pixels. All my other tests use MVBP values other than zero and are drawn correctly in UAE.

**Comment by tonioni** [comment]
I finally debugged this. It was stupid bug in early exit optimization condition (which was added later, after collision emulation was already complete) which triggered in some situations even when new collisions was possible. Fixed.
