### ISSUE TITLE
Any chance to make the gui dynamic with Desktop fontsize?

### ISSUE THREAD

**Issue by CypherXG** [tonioni/WinUAE#155]
Hello
I'm using a 4k Monitor with a resolution 3840x2160px
When i change the desktop Font size bigger than 100% like 150% the Gui from Winuae ist moved like in the picture. 
Is it possible to make a gui with a dynamic window? 

<img width="436" alt="Unbenannt" src="https://user-images.githubusercontent.com/7895130/62569082-894e7d00-b88e-11e9-98b4-d241a62e3f15.PNG">

Best regards
Markus

**Comment by tonioni** [comment]
Current alpha/development version should already fix this problem. High DPI support was rewritten.
http://www.winuae.net/files/b/winuae.7z

**Comment by CypherXG** [comment]
Perfect...
It's working....

One question...
Is it possible to add ".bin" in the file Filter when i try to add a rom for a Accelerator board Rom File?
Most files or rom dumps have a .bin extension.
So i must rename all files from .bin to .rom
To add this feature would be also nice so Winuae can regonize all roms with the rom scan option without renaming.

Best regards..
Markus

**Comment by tonioni** [comment]
Will be added (or you can set windows dialog filter to all files and it will be remembered)
