### ISSUE TITLE
Issue with horizontal sprite multiplexing

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#158]
Hi Toni,

to get „R-Type II“ working in vAmiga, I’ve implemented horizontal sprite multiplexing and started by setting up a simple test case:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/Sprites/multiplex1

The two multiplexed coordinates of the last sprite are shifted so close together that the sprite overlaps itself. On an original A500 it looks like this: 

![multiplex1_A500_6A](https://user-images.githubusercontent.com/12561945/66648768-aad03a00-ec2c-11e9-96ac-4be8e805688b.jpeg)

When I run the test case in UAE, I noticed that it looks slightly different compared to the original machine. The two sprites at the bottom are melted together:

<img width="719" alt="Bildschirmfoto 2019-10-11 um 11 16 21" src="https://user-images.githubusercontent.com/12561945/66648786-b7ed2900-ec2c-11e9-81ba-aa0d193a2579.png">

Please note that the A500 photo has awful colour quality. In reality, the colours on the monitor look similar to what UAE is displaying.

**Comment by tonioni** [comment]
I'll test later but I have a request: could you make your test cases plain executables (that also work with fast ram)? It is far easier to transfer, select and run when using ACA500plus. Transferring adfs is painful.

**Comment by dirkwhoffmann** [comment]
Here we go: 

[main.bin.zip](https://github.com/tonioni/WinUAE/files/3721607/main.bin.zip)

**Comment by mithrendal** [comment]
>I'll test later but I have a request: could you make your test **cases**..

@dirkwhoffmann Did you noticed the plural  ? Seems like toni wants all test **cases** from the [vAmigaTestSuite ](https://github.com/dirkwhoffmann/vAmigaTS) uploaded as a plain executable ? For me when I test them on my A1000 Agnus8367R0 that would also be super convenient, as I could copy them all onto one ADF and transfer them in just one step to the Amiga1000. Even more cool if the name of the executables would be names of the test cases. Maybe it is possible in your build chain to easily side generate those executables ? No?

**Comment by tonioni** [comment]
Fixed.

And yes, single archive of all tests (at least same test type) would be useful.
