### ISSUE TITLE
Copper tests jump1b and jump1c fail in UAE

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#161]
Hi Toni,

I wrote a bunch of Copper tests for verifying Copper timing in vAmiga. Two of these tests fail in UAE, too. 

The details are here: 

https://github.com/dirkwhoffmann/vAmiga/issues/204
https://github.com/dirkwhoffmann/vAmiga/issues/209

Unfortunately, I didn’t manage to modify my tool chain yet to produce EXE files instead of ADFs. 
You’ll find the ADFs in the vAmigaTS repo at: 

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Copper/Jump/jump1b
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Copper/Jump/jump1c

There you will also find the Copper lists. They are very simple, so you may not even need the ADFs.

**Comment by tonioni** [comment]
Fixed in 4.3.0
