### ISSUE TITLE
CIA TOD issues

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#165]
Hi Toni,

I stumbled across the „TOD bug“ and started to support it in vAmiga. For doing this, I’ve written two test cases that play around with the TOD registers:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/CIA/tod/todbug1
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/CIA/tod/todbug2

This is test case "todbug1" on a real A500: 

![todbug1_A500_8A](https://user-images.githubusercontent.com/12561945/74146079-9a42c700-4c00-11ea-9ccb-d2ad93ae9e2b.JPG)

As expected, this test fails in vAmiga and passes in UAE. However, when I try to disable "TOD bug" emulation in UAE, it doesn’t seem to have an effect. It seems like the TOD bug is always emulated in UAE no matter what I select here: 

<img width="781" alt="Bildschirmfoto 2020-02-10 um 12 14 16" src="https://user-images.githubusercontent.com/12561945/74146136-be060d00-4c00-11ea-9a66-92748436a97c.png">

This is test case "todbug2" on a real A500:

![todbug2_A500_8A](https://user-images.githubusercontent.com/12561945/74146100-a464c580-4c00-11ea-9b5f-535f69a83485.JPG)

This test has nothing to do with the TOD bug, because it verifies that TODHI is *not* affected by the counting error. This test fails in UAE though:

<img width="721" alt="Bildschirmfoto 2020-02-10 um 12 15 47" src="https://user-images.githubusercontent.com/12561945/74146120-b2b2e180-4c00-11ea-8e25-c908ffb73930.png">

The erroneous area checks that a TOD IRQ is triggered when the alarm is set to 000000 and the TOD clock wraps around from FFFFFF to 000000. It seems like UAE does not trigger the IRQ in this case.

**Comment by tonioni** [comment]
Did you quit emulation when changing the option? Not all options change on the fly but needs restart.

**Comment by dirkwhoffmann** [comment]
> Did you quit emulation when changing the option?

No, I only hit reset. This might be the reason.

**Comment by dirkwhoffmann** [comment]
> No, I only hit reset. This might be the reason.

I can confirm that quitting and restarting does update the TOD bug setting.
