### ISSUE TITLE
CIAB CNT pin issue

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#166]
While studying the A500 schematics, I’ve encountered that CIAB::PA1 is directly connected to the CNT pin. To support this in vAmiga, I’ve written a test case that sets up a timer and counts that timer down by manually generated pulses on PA1. To visualise the result, my test case copies the low byte of the timer to the background color register. 

<img width="541" alt="Bildschirmfoto 2020-02-18 um 10 19 52" src="https://user-images.githubusercontent.com/12561945/74722784-cc27df00-5239-11ea-9512-f57c1af7dcae.png">

On a real A500, it looks like this: 

![cnt1_A500_8A](https://user-images.githubusercontent.com/12561945/74722811-d518b080-5239-11ea-8762-0799e113e331.JPG)

In UAE, it looks like this: 

<img width="719" alt="Bildschirmfoto 2020-02-18 um 10 23 49" src="https://user-images.githubusercontent.com/12561945/74722791-cf22cf80-5239-11ea-8d7b-adba411b6c1c.png">

**Comment by tonioni** [comment]
I have completely missed that connection. Interesting detail, CIA can both send and receive serial data to itself :)

**Comment by tonioni** [comment]
Mostly implemented now but untested (both directions).

But there is also another unimplemented CIA weird feature that no one uses: PBON+OUTMODE. CIA-A PBx connects to parallel port so there is no way to read pin status without extra hardware but CIA-B PB7 and PB6 are /MOTOR and /SEL3 so if you want to be tricky, you can start and stop floppy motor using timer and read motor status using /RDY or index sync interrupts..

**Comment by dirkwhoffmann** [comment]
> you can start and stop floppy motor using timer and read motor status using /RDY or index sync interrupts.

You mean by setting bit 1 in CIAB::CRA (resp. CIAB::CRB) to 1 which causes the CIA to indicate timer underflows on port pin 6 (resp. 7). 

Controlling the drive motor by timer underflows is definitely a killer feature. I think this is why people said the Amiga was way ahead of it's competitors back in the days 😂.

I am curious if this motor thing works in vAmiga. I've taken the CIA implementation from VirtualC64 which should emulate the PA6 / PA7 feature correctly. On the other hand, there is software engineering rule number 1: Nothing works that hasn't been tested. So I better write a test case for that...

**Comment by tonioni** [comment]
Yeah, bit 2 (OUTMODE) also needs to be set because without it PB7/PB6 only pulses for one clock cycle when timer underflows. (At least according to documentation)

6526 should be functionally identical to 8520 except TOD is 4-register BCD and timer won't start automatically when timer high register is written in oneshot mode.
