### ISSUE TITLE
Possible issue with POTxDAT

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#167]
I’ve written a potentiometer test that sets the START bit in POTGO to 1 inside the VSYNC handler and lets the CPU execute the following loop: 

```
.mainLoop:
    move.w  VHPOSR(a1),d0
    sub.w   #$800,d0
    move.w  POT0DAT(a1),d1
    and.w   #$FF00,d0
    and.w   #$FF00,d1
    cmp.w   d0,d1
    beq     .equal  
    move.w  #$F00,COLOR00(a1)
    bra.b   .mainLoop 
.equal:
    move.w  #$0F0,COLOR00(a1)
    bra.b   .mainLoop
```

In short:

Background color is green or red
Background color is green <=> VPOS - 8 == POT0DAT

On the real machine, the condition holds for all visible scanlines. 

![pot0dat0](https://user-images.githubusercontent.com/12561945/74741683-9137a280-525d-11ea-8392-43df2130eae3.JPG)

No device was attached to the control ports of my test machine. Hence, the default resistances on the paddle pins (if no device is attached) don't stop the counters. 

UAE produces the following:

<img width="719" alt="Bildschirmfoto 2020-02-18 um 14 39 08" src="https://user-images.githubusercontent.com/12561945/74741704-9a287400-525d-11ea-8836-725129ef54de.png">

I am wondering if UAE connects something to the paddle pins by default... 🤔

**Comment by tonioni** [comment]
"Not enough information". In other words: test program required because there are too many unknown variables, like state of other pot bits and other port related configuration.

(btw, better write to POTGO during visible part of display because something can happen during first ~10 lines)

**Comment by dirkwhoffmann** [comment]
Test case is located here:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Ports/POT/cmp0hi

The repo contains the source code and an ADF (I am still not able to produce exe files with my tool chain).

**Comment by tonioni** [comment]
Confirmed. There was a bug, POTGO/POTxDAT accesses affected POTxDAT counting, not just hsync.

btw, there is also sort of undocumented behavior: there are 2 types of mice. Some mice have pullup resistors in button lines, some don't.  UAE by default emulates mouse with pull up resistors because it is more compatible with less than good button read routines.

**Comment by dirkwhoffmann** [comment]
> there are 2 types of mice. Some mice have pullup resistors in button lines, some don't.

Thanks, this is valuable information for my own emulator!

If I understand this correctly, this affects the situation where DATLY (mouse in port 0) or DATRY (mouse in port 1) in POTGO is (accidentally) configured as input. For a normal mouse (without pull-up resistors), this line would be 0 if the button is pressed and in a floating state otherwise. For a mouse with pull-up resistors, the value would be 0 if the button is pressed and 1 (Vcc) if it is released. When the line is configured as output, there is no difference, because the value in POTGO drives the line.

Is this correct?

**Comment by tonioni** [comment]
Correct except output mode. In output mode pin level can be still read (if it is driven by some external device). This is documented in HRM, is perfectly safe and normal method to read buttons 100% reliably, with or without pullup resistors. Using input mode + no pullups would not work. Output mode is basically internal pullup.
