### ISSUE TITLE
Running "bustest" freezes emulation when using JIT

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#168]
Running bustest (http://aminet.net/package/util/moni/bustest) freezes emulation, if JIT is enabled.

To Reproduce
* Unpack bustest
* run for instance `bustest chip size=1024`
* after a few seconds, the emulation freezes, but you can return to the GUI.

Example screenshot:
![image](https://user-images.githubusercontent.com/3877365/74932443-1ba90f00-53e2-11ea-97d3-19d673322879.png)

Originally reported here: https://github.com/midwan/amiberry/issues/569

**Comment by tonioni** [comment]
Outer loop counter contains something that probably is not correct (slightly under half of max 32-bit value) which means the test loop will run for a very very very long time..

Not worth to trouble to debug without sources or someone resourcing it first.. It could be JIT bug or program bug when CPU is really really too fast. Most likely program bug if it also happens with ARM JIT.

**Comment by midwan** [comment]
Thanks for the feedback!
