### ISSUE TITLE
Wrong value in CIA A SDR register in keyboard resync mode

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#169]
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Ports/Keyboard/noack1

This test verifies the keyboard behaviour when the Amiga omits to send the acknowledge signal after a keycode has been received. The test reads the contents of CIAA::SDR in the IRQ level 2 handler and displays the result in the upper part of the screen. It also keeps track of how many level 2 IRQs have been issued and displays the counter value in the lower part of the screen. To start the test, hit any key to call the level 2 handler. Because the handler omits to send the acknowledge signal, the keyboard switches to a special state where it tries to resynchronize with the Amiga. In this state, it transmits a one bit every 145 ms which means that the IRQ handler is called again and again with a delay of approx. 1.2 sec. The test case visualizes this: After pressing a key, the upper color bars turn black (because the 1's are received as 0's) and the lower part shows a counting pattern that changes every 1.2 sec.

On my A500 it looks as expected: 

![noack1_A500_8A](https://user-images.githubusercontent.com/12561945/75042625-fe963e00-54be-11ea-9863-6837fe135031.JPG)

In UAE it looks like this (only the upper part is relevant, because the lower part is the IRQ counter):

<img width="719" alt="Bildschirmfoto 2020-02-21 um 15 18 18" src="https://user-images.githubusercontent.com/12561945/75042632-035af200-54bf-11ea-93c3-4133cab5d90b.png">

UAE does count (it does send the acknowledge pulses), but the SDR contents is not changed to zero. It keeps on showing the old SDR value (old value = keycode of the key that hasn’t been acknowledged).

**Comment by tonioni** [comment]
Fixed. I thought CIA SDR won't get updated (copied from internal buffer) until it has been read first but it gets overwritten every time 8 bits have been received. There is not even any overflow flags..
