### ISSUE TITLE
[ENHANCEMENT] Include @mattiasgustavsson 's scanlines shader

### ISSUE THREAD

**Issue by SylvainDebaudringhien** [tonioni/WinUAE#173]
@mattiasgustavsson created a really good looking scanlines shader:
![Capture-1](https://user-images.githubusercontent.com/12871704/81056752-5abc0c00-8ecb-11ea-8c37-fe6ea7ab91be.png)
https://github.com/mattiasgustavsson/steem-crt
https://mattiasgustavsson.itch.io/steem-crt

It is currently working with STEEM (ST) and DosBox.
It would be amazing to have it in WinUAE! :)

**Comment by tonioni** [comment]
I don't do shaders (I prefer pixel perfect sharp display) but similar crt shaders are available here: http://eab.abime.net/showthread.php?t=61776

**Comment by SylvainDebaudringhien** [comment]
Thanks, gonna check that out! :)
