### ISSUE TITLE
Internal drive test of Logica Diagnostica Cartridge can't be run

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#174]
I tried to run the internal drive test included in the Logica Diagnostic Cartridge.

<img width="721" alt="Bildschirmfoto 2020-05-24 um 14 43 18" src="https://user-images.githubusercontent.com/12561945/82754474-65343c00-9dcd-11ea-861c-fd55bdaee9e7.png">

When I start the test, UAE says this:

<img width="721" alt="Bildschirmfoto 2020-05-24 um 14 43 29" src="https://user-images.githubusercontent.com/12561945/82754480-6d8c7700-9dcd-11ea-94e1-a2d725f71e8b.png">

UAE was configured to emulate an A500 with 100% floppy drive emulation speed.

I’m not sure if it’s a bug. Maybe there is some additional compatibility setting I am not aware of? 🤔

**Comment by tonioni** [comment]
It was a bug, already fixed in 4.4 betas. When Amax ROM adapter support was added long time ago, it broke disk DMA getting enabled without any drives selected. (It was instantly finished). It looks like this test program starts DMA first, then selects drive(s).
