### ISSUE TITLE
Small issue with "Amiga audio hardware trivia"

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#175]
I’ve just read the article "Amiga audio hardware trivia" on EAB with great pleasure and played around with the program at the end of the thread.

https://eab.abime.net/showthread.php?t=54961

In my own program, I changed the „IRQ launch sequence“ to this: 

```
    move.w #$8201,DMACON(a1)  ; Aud0 DMA on
    move.w #$0201,DMACON(a1)  ; Aud0 DMA off

    move.w #300,d0            ; Skip at least one rasterline
.l0:
    dbra   d0,.l0

    move.w #$8200,DMACON(a1) ; DMA enable
```

On the real machine, the IRQ still kicks in: 

![pertimer1](https://user-images.githubusercontent.com/12561945/84026606-e96dee00-a98d-11ea-8eaa-e84e81fd70c1.JPG)

In UAE 4.3.0, I get a black screen. 

Here is the test case in form of an ADF: 
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Audio/simple/pertimer1

**Comment by tonioni** [comment]
I think this is previously unknown undocumented feature.

It looks like Agnus latches Paula DMA requests and DMA request is only cleared when DMA access is done (=DMA master bit is back to one. Note that Agnus ignores audio and disk DMA bits!) and it is not cleared if DMA is off.

I get similar output if I don't clear Paula DMA request until "successful" AUDxDAT write.

I assume same happens even if you wait multiple frames? To confirm there is no weird and unexpected reset condition during vertical blank.

(btw, now you really should generate plain executables because it probably is faster to copy them to CF card and insert in ACA500plus than to use floppy emulator and boot from slow floppy :))

**Comment by dirkwhoffmann** [comment]
> It looks like Agnus latches Paula DMA requests and DMA request is only cleared when DMA access is done

Yes, I think this is what happens. In vAmiga I implemented it this way (by coincidence) and the test case worked. I wish it had been the other way round, because I want to find bugs in vAmiga. 

> I assume same happens even if you wait multiple frames? 

I'll check that.

 > (btw, now you really should generate plain executables because it probably is faster to copy them to CF card and insert in ACA500plus than to use floppy emulator and boot from slow floppy :))

Yes, but then I can't load the test cases in vAmiga any more 😅. My A500 has a Gotek drive, so I usually copy the ADFs to a memory stick and boot from there. At least my test cases should be cleaner now. They use the "ministartup" code you've pointed me to.

**Comment by dirkwhoffmann** [comment]
When the delay loop is replaced by

```
    move.w #$FFFF,d0
.l0:
    dbra   d0,.l0
```

the A500 shows a solid magenta screen. It seems like the AUDxDAT write is happening in the next line although the master enable bit is cleared. Originally, I thought my code would postpone this write until the master enable is set back to 1, but this doesn't seem to be the case.

**Comment by tonioni** [comment]
I think I have better explantion :)

Assuming your 300 delay wasn't too long, my guess is that next scanline's DMAL transfer will actually replace previous latched DMA request bits with new request bits. But if old latched request was already enabled from previous scan line, DMA request is still processed by Agnus before it gets cleared.

**Comment by tonioni** [comment]
Correct explanation after some tests: Paula checks DMACON DMAEN bit when any audio channel wants to generate DMA request. If DMAEN is cleared, no request will be sent. Agnus ignores DMACON contents completely if request comes from Paula (via DMAL). 

Which means Agnus will do audio DMA access even if DMAEN is cleared after Paula internally decided that DMA is needed but before Agnus knows about it.
