### ISSUE TITLE
https - encrypted connection

### ISSUE THREAD

**Issue by marcoagpinto** [tonioni/WinUAE#176]
Hello!

I e-mailed you months ago regarding the subject.

Why can't SSL be added to the site?

There is a very used free certificate "Let's Encrypt". Even the Portuguese military use it in their site.

I and many other people no longer download executables from sites that don't show secure on the browser.

Thanks!

**Comment by tonioni** [comment]
I thought I replied. I don't host the server (I don't want to. Everything not directly UAE related is someone else's problem :)).

It is hosted by abime.net and it gets SSL when it gets transferred to new server which should happen sometime this year.
