### ISSUE TITLE
Inconsistent naming for comp_catchfault setting

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#177]
Hi Toni,

The naming of the `comp_catchfault` setting in the config file is inconsistent:
It's named `comp_catchdetect` when writing to the file, but named `comp_catchfault` when it's parsed.

Affected areas:
cfgfile.cpp, lines 1992 (write) and 5455 (read).

**Comment by tonioni** [comment]
This was fixed some time ago. Thanks for reporting.
