### ISSUE TITLE
Graphics mismatch if HAM + DPF is enabled

### ISSUE THREAD

**Issue by dirkwhoffmann** [tonioni/WinUAE#178]
Hi Toni,

I did some experiments with BPLCON0 and dared to set both the HAM bit and the DPF bit simultaneously.

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/block3m

Fortunately, the real machine did not explode. Instead, it produced the following picture:

![block3m_A500_8A](https://user-images.githubusercontent.com/12561945/88924768-fc0cf100-d273-11ea-8f79-dca1d47a3c9b.JPG)

This is how it looks in UAE:

<img width="721" alt="Bildschirmfoto 2020-07-30 um 14 33 23" src="https://user-images.githubusercontent.com/12561945/88924800-04fdc280-d274-11ea-8410-f481bbdf39e9.png">

I think I know what’s going on in this (illegal) mode. If HAM and DPF are both selected, Denise draws in HAM mode. Just as in standard HAM mode, the bits of the two uppermost bitplanes decide whether a color component is replaced, but the replacement scheme is different. If a color component is replaced, not the raw bitplane data is substituted, but the color index of the visible playfield. I did this in vAmiga and got the correct picture: 

<img width="908" alt="Bildschirmfoto 2020-07-30 um 14 48 45" src="https://user-images.githubusercontent.com/12561945/88924829-0d55fd80-d274-11ea-9838-889703d21531.png">

Other test cases using this (illegal) mode are here:

https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/ham3
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/block3
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/modes3
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/modes3b
https://github.com/dirkwhoffmann/vAmigaTS/tree/master/Denise/BPLCON0/modes3c

**Comment by tonioni** [comment]
Strange that no one has used that "mode". I think I also quickly checked this combination (probably was 10years+ ago) but I guess I used bad test setup.

Did you also check if BPLCON2 DPF bits affect the display? Including using "illegal" priority values  (5, 6 or 7) that cause playfield to become COLOR0 but still hiding possible bitplane behind it in normal dpf mode.

**Comment by dirkwhoffmann** [comment]
> Did you also check if BPLCON2 DPF bits affect the display?

No, I haven't checked this yet. My guess is the effect works as usual, because colorization happens at a later stage in the graphics pipeline (but it's just a guess).

>  Including using "illegal" priority values (5, 6 or 7) that cause playfield to become COLOR0 but still hiding possible bitplane behind it in normal dpf mode.

BTW, is there a game or demo which relies on this oddity?

**Comment by tonioni** [comment]
Guesses are not allowed! :)

Running man / Scoopex does something similar. (Logo fade is wrong if this is not handled correctly)

**Comment by tonioni** [comment]
Could you explain more clearly what do you mean by replacing color index? I am too lazy to do real A500 tests after that annoying "DMA off" side-effect :)
Did you already test what happens if BPLCON2 dual playfield priority bit is toggled?

**Comment by dirkwhoffmann** [comment]
> Could you explain more clearly what do you mean by replacing color index? 

With color index I meant the number of the color register that would be chosen in (non ham) dual playfield mode. If the dual playfield bit is set, Denise first splits the bitplane data into the two color indices and picks one of them depending on playfield priority. After that, she evaluates the HAM bit and does the normal HAM stuff if it is enabled. If a color component is to be replaced, she replaces the R, G, or B part by the previously picked index. 

> Did you already test what happens if BPLCON2 dual playfield priority bit is toggled?

No 🙄. Most of the time during the last weeks, I was trying to hunt down a stupid bug in vAmiga which is killing my nerves (https://github.com/dirkwhoffmann/vAmiga/issues/348). My emulator hates me 😖.

**Comment by tonioni** [comment]
Thanks. Everything else looks now correct expect that yellow line. I can't get rid of it :) (and I did confirm that A1000 also shows exact same image as your A500)

**Comment by tonioni** [comment]
Yellow line is also gone (related to previous BPLxDAT timing update).

DPF plane priority and illegal priority values work identically to normal DPF mode. I still have one remaining issue: if both priority values are illegal (BPLCON2 = 0x003f), part of bars at the bottom of screen don't disappear. Whole screen becomes blank on real hardware.

**Comment by tonioni** [comment]
Illegal DPF priorities fixed. (DPF illegal BPLCON2 emulation didn't work correctly in hires mode)
