### ISSUE TITLE
Joystick gets stuck if mapped to a POV hat

### ISSUE THREAD

**Issue by arisklapachi** [tonioni/WinUAE#180]
If custom input map is used with host's POV hat mapped to emulated joystick directions, and if hat's direction changes rapidly in-game, for example, from up+left to down+right and then again to up+left, the joystick gets stuck being pressed up+right in Lethal Xcess and down+right in Agony until the hat is released. Works OK with mapped buttons or analog axes.
Map config window screenshot:
![image](https://user-images.githubusercontent.com/6189315/90390545-ddf61c00-e0ce-11ea-9f22-2951f9fa4a5f.png)

**Comment by tonioni** [comment]
[-] and [+] event types are meant for button-like (on or off only) input device use only. These events don't necessarily work as expected when they are used with other input types (which have more than 2 states)

Select first entry (Joy 2 left), then click Remap. Move hat left, right, up, down and it should automatically combine left/right and up/down to correct events. ("Hat Switch (X)" = left/right and "Hat Switch (Y)" = up/down).
