### ISSUE TITLE
PhxAss fails on filesys_helpers.asm

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#183]
Hi Toni,

I've been trying to prepare the filesys.asm for Amiberry (slightly modified, I've left out the 060 fpu disable and debugger support since that's not implemented), but I'm having trouble when using PhxAss:

```
phxass filesys.asm to fs.out
```
Returns with errors about the C code in the `filesys_helpers.asm` file. I've removed that piece, since it's supposed to be disabled anyway from what I can see, and then I get the following instead:

![image](https://user-images.githubusercontent.com/3877365/93685969-68a5ae80-fab3-11ea-9df5-5fb2fc8494a7.png)

Which assembler am I supposed to use, if not PhxAss, to prepare this?

**Comment by tonioni** [comment]
I have used latest asmone but vasm also seems to work (with -m68060 parameter). Try newer phxass because your error screenshot does not make any sense.

**Comment by midwan** [comment]
@tonioni 
Thanks!
I assume that the resulting `filesys_bootrom.cpp` is already correct however, right?
I opted to use that directly, and it seems to work.

**Comment by tonioni** [comment]
Binary and resulting filesys_bootrom.cpp are correct versions. (My Amiga asm file compilation directory is different than source tree directory)

**Comment by midwan** [comment]
Alright, thanks!
