### ISSUE TITLE
link to http://www.winuae.net/files/b/winuaeinclibs.zip is broken

### ISSUE THREAD

**Issue by rsr-at-mindtwin** [tonioni/WinUAE#185]
in the readme,

Download Link -> http://www.winuae.net/files/b/winuaeinclibs.zip

this results in a 404.

**Comment by tonioni** [comment]
Yeah, download redirect got broken when https support was added. It should get fixed sooner or later.

https://download.abime.net/winuae/files/b/winuaeinclibs.zip should work until it gets fixed.

**Comment by arutkowski00** [comment]
> https://download.abime.net/winuae/files/b/winuaeinclibs.zip should work until it gets fixed.

@tonioni Well, this link doesn't work either.

**Comment by mfn** [comment]
The link seems to have a referred protection. If I click it here, from githubs page directly, it's a 403.

If I copy it into a new tab, it works.

I noticed this because from my notification email, the link did work. But not from here.

**Comment by rsr-at-mindtwin** [comment]
Thanks for looking into it.

**Comment by rofl0r** [comment]
why is this issue closed ? the link is still not fixed in README.

btw it's super easy to attach a .zip file to *any* comment in github, and then use the link from that comment, in case hosting is the issue here.

**Comment by tonioni** [comment]
It was supposed to be fixed but it looks like only some paths redirect correctly after HTTPS was implemented.
URLs fixed.

**Comment by lab313ru** [comment]
No, the url is forbidden.
