### ISSUE TITLE
SCP floppy image doesn't wrap to revolution #0 cleanly (includes patch)

### ISSUE THREAD

**Issue by keirf** [tonioni/WinUAE#186]
A single-revolution generated SCP image containing a non-index-aligned track ought to be able to replay cleanly if flux is precisely accounted across the wrap-round. This isn't currently the case as "flux gap" from the last sample to the track-end time is currently lost. The patch I attach below fixes this. I also include an example SCP file which exhibits the issue.

The patch also fixes a long-standing bug where revolution #0 in a multi-revolution image gets played out twice when a track is first loaded. eg. in a four-rev file the emulator will see revs 0,0,1,2,3,0,1,2,3,0,1,2,3,...

NOTE: The patch is against FS-UAE, but I believe the code in question is identical between the UAEs and should apply cleanly.

[scp.zip](https://github.com/tonioni/WinUAE/files/5577405/scp.zip)

**Comment by tonioni** [comment]
Done
