### ISSUE TITLE
Blackerthanblack option seems to do the opposite?

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#189]
Hi Toni,

I noticed that the option `gfx_blackerthanblack`, which is supposed to make the blank border area darker than the RGB "black", seems to be doing the opposite.

Indeed, in `gfxutil.cpp`, it seems to add `10` to the RGB values, e.g.:
```
if (currprefs.gfx_blackerthanblack) {
			r += 10;
			g += 10;
			b += 10;
			if (r > 255)
				r = 255;
			if (g > 255)
				g = 255;
			if (b > 255)
				b = 255;
		}
```

Is this a mistake? Should that `if` be checking for the opposite (`!currprefs.gfx_blackerthanblack)` perhaps?

**Comment by tonioni** [comment]
It is correct, it slightly increases brightness of "normal" black to make it look like borderblanked black is blacker. It is impossible (at least without HDR) to make actual blacker black.

**Comment by midwan** [comment]
Thanks for clarifying that! :)

**Comment by khval** [comment]
How about, changing it, to reduce overexposure.

if (currprefs.gfx_blackerthanblack) {
   r=(r*(255-10)/255)+10;
   g=(g*(255-10)/255)+10;
   b=(g*(255-10)/255)+10;
}

**Comment by tonioni** [comment]
I tried to keep most original values untouched but I guess this is better way (AGA color selection already did something similar)
