### ISSUE TITLE
Bug in cia.cpp, restore_cia(...)

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#194]
The lines

	if (num) ciabsdr_cnt = b; else ciaasdr_cnt = b;
	if (num) ciabsdr_buf = b;

should be replaced with

  	if (num) ciabsdr_cnt = b; else ciaasdr_cnt = b;
  	b = restore_u8 ();
	if (num) ciabsdr_buf = b; else ciaasdr_buf = b;

**Comment by tonioni** [comment]
Fixed, thanks. (Probably didn't affect anything because CIA-B serial port is practically never used except perhaps with some diagnostics hardware)
