### ISSUE TITLE
Bug in blkdev.cpp, save_cd(...)

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#195]
Replace line

dstbak = dst = xmalloc (uae_u8, 4 + MAX_DPATH + 4 + 4 + 4 + 2 * MAX_DPATH);

with

dstbak = dst = xmalloc (uae_u8, 4 + MAX_DPATH + 4 + 4 + 4 + SUBQ_SIZE + 2 * MAX_DPATH);

**Comment by tonioni** [comment]
Fixed

**Comment by rofl0r** [comment]
@PandTomB the master bug hunters! i wonder how they find all these bugs...
