### ISSUE TITLE
Bug in restore_expansion_finish()

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#197]
At the end of the function restore_expansion_finish(), you should add this line:
restore_cardno = 0;

Otherwise the emulator crashes in following scenario:
 - Load config which uses UAE expansion board/Boot ROM
 - Run emulation, load saved state for this configuration, continue emulation
 - Load different configuration which also uses expansion components, run emulation
 -> crash.

**Comment by tonioni** [comment]
Fixed few betas ago. (But it still can crash in some situations with enough expansion boards, need to fix someday..)
