### ISSUE TITLE
Jesus on E's demo - credits scene

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#211]
I noticed this in Amiberry, so I tested it on WinUAE 4.9.1 as well, and I can see it does the same thing.
The demo Jesus on E's shows a black screen during the end/credits scene, but if you open the emulator GUI and change the Chipset option to OCS or ECS, the screen shows the right thing. You can open the GUI and change chipset settings again after that, and it remains correct.

Steps to recreate:
- Get the demo disks from Aminet or also uploaded here for convenience: [JonEs.zip](https://github.com/tonioni/WinUAE/files/8216492/JonEs.zip)
- Use a Quickstart configuration of A600, you can also use both DF0 and DF1 to avoid disk swapping
- Boot the demo and let it run for the whole 27 minutes (sorry about that, the credits scene is at the end)
- When it reaches the credits scene, you can hear the music but the screen is all black.
- If then you open the GUI, and change the Chipset option from Full ECS (if you used the A600 config) to ECS Agnus or OCS, then resume, the screen is no longer black and shows the expected graphics.

Let me know if you need anything else to recreate this!

**Comment by tonioni** [comment]
It looks to be correct behavior. There are multiple demos that have blank screen if ECS Denise. They set up out of range horizontal display start and end which accidentally works on OCS Denise (because it has sort of a bug). ECS Denise (and AGA) does not anymore support it.
