### ISSUE TITLE
HDD file path issue

### ISSUE THREAD

**Issue by Artik-joachim** [tonioni/WinUAE#220]
I am running Winuae 4.9.0 64 bit from the following windows folder: 
`C:\Users\USER\AppData\Roaming\Code\User\globalStorage\prb28.amiga-assembly\downloads\vscode-amiga-assembly-binaries-@-1.4.0\vscode-amiga-assembly-binaries-windows_x64`

DH0 is located here:
`C:\dev\Amiga-asm\uae\A1200dh0`

I get the floowing error in winuaelog.txt:
```
08-169 [28 185-123]: Mounting uaehf.device:0 0 (0):
08-169 [28 185-123]: FS: mounted virtual unit DH0 (..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0)
08-312 [35 001-103]: FS: dh0 (flags=00000002,E=0,ED=1,EF=0,native='..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0') starting..
09-100 [75 000-001]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DOSDrivers\PIPE.info') failed! error=3, aino=000000001AD4F610 dir=0
09-218 [80 227-190]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\Monitors\PAL.info') failed! error=3, aino=000000001AD50990 dir=0
09-476 [93 045-282]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\8SVX.info') failed! error=3, aino=000000001AD50F90 dir=0
09-476 [93 000-284]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\AmigaGuide') failed! error=3, aino=000000001AD50810 dir=0
09-476 [93 227-285]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\AmigaGuide.info') failed! error=3, aino=000000001AD51290 dir=0
09-477 [93 227-291]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\ANIM.info') failed! error=3, aino=000000001AD50810 dir=0
09-477 [93 227-298]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\CDXL.info') failed! error=3, aino=000000001AD50490 dir=0
09-477 [93 227-304]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\FTXT.info') failed! error=3, aino=000000001AD50810 dir=0
09-477 [93 086-311]: GetFileAttributes('..\..\..\..\..\..\..\..\..\..\..\dev\Amiga-asm\uae\A1200dh0\devs\DataTypes\ILBM.info') failed! error=3, aino=000000001AD50510 dir=0
```

In WINUAE, I get weird issues, for example, I cannot access the inputs.prefs.

When WinUAE is located in `C:\dev`, there is no issue.

is there an issue with the size of the path for accessing DH0 ?
thx

**Comment by tonioni** [comment]
Quite deep relative path. WinUAE in relative paths mode always converts all paths that are directories under WinUAE exe path to relative. Perhaps this is too deep relative path but mounting still succeeds. (E=0 would become E=1 meaning empty/non-existing)

Does all files return same error or only some files? Perhaps whole path (original absolute path + ..\...\ and so on) gets combined and becomes too long internally?

Does filesystem_mangle_reserved_names=false UAE config file entry help?
What if you disable Windows 260 character PATH limit? (https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation) WinUAE internally supports at least 1000 character paths.
