### ISSUE TITLE
Recoverable alert after CIA rewrite

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#221]
Hi Toni,

I had an issue reported in Amiberry, after merging the recent changes you committed to WinUAE as well: https://github.com/BlitterStudio/amiberry/issues/985
I traced this in WinUAE as well, and it's coming from commit 81a5c2b05a8f1c7b5b91ae2d7625495a84d2c46e

Before that, there's no Guru - with that, it starts happening up to the latest commit you have in the repo.

**Comment by tonioni** [comment]
This should be fixed now. If CPU mode was "too fast", multiple CPU instructions could execute during single CIA cycle which won't work very well if CIA emulation includes internal delays.

**Comment by midwan** [comment]
Confirmed this works as expected, in the latest version
