### ISSUE TITLE
A2024 monitor emulation becomes a flickering mess when window re-sized

### ISSUE THREAD

**Issue by BrianHoldsworth** [tonioni/WinUAE#234]
I believe support for the Commodore A2024 high-resolution, gray-scale monitor was added in v4.3. However, I have only just tried it out with v4.9.1 for Win64.

My steps to reproduce:
1. Create a configuration with KS 3.1, ECS, 68020/68881 CPU/FPU, 1M CHIP and 8M FAST. Additionally enable the A2024 monitor in the "Chipset" panel.
2. Fresh install of Workbench 3.1 from floppies.
3. Drag the A2024 monitor driver file from Storage/Monitors to Devs/Monitors.
4. Reboot and select an A2024 mode in Prefs/Screenmode. Either 10Hz or 15Hz mode; doesn't matter.

With the Display in windowed mode, the A2024 emulation will work, though the window is far too small to be usable in my case. This is shown in "Capture1" image attached.

If I resize the window to make it bigger, or switch into Fullscreen mode, then the emulated display turns to a jumbled mess as show in "Capture2" attached. Starting out with an enlarged window of fullscreen, before switching to an A2024 screen mode, also has the same problem.
![Capture1](https://user-images.githubusercontent.com/731176/201167335-60f4f493-1199-488d-98dd-f41bd4ea359a.PNG)
![Capture2](https://user-images.githubusercontent.com/731176/201167337-ddf2080d-e784-4e2b-bf64-b70f13c55ab8.PNG)

**Comment by tonioni** [comment]
Hi, make sure Filter panel is set to "no scaling" because filter scaling might corrupt (or snip completely) A2024 control signals in hidden lines before display starts. No control signals detected: "raw" data is visible (same that you would see when in A2024 mode but using normal monitor)

A2024 is too weird (and almost useless), it is not worth the trouble to support it in all modes and/or scale the display :)

**Comment by BrianHoldsworth** [comment]
@tonioni Thanks. Indeed, you are correct, and setting the "No scaling" option in the Filter pane renders the screen correctly (see below).

> A2024 is too weird (and almost useless),

I consider it weird, wacky, and wonderful :) And so I'm very glad this workaround exists. Issue should probably be closed, with the workaround noted.
