### ISSUE TITLE
debugmem.cpp@branch_stack_push can overflow

### ISSUE THREAD

**Issue by BartmanAbyss** [tonioni/WinUAE#240]
`stackframecnt` and `stackframecntsuper` are not checked against `MAX_STACKFRAMES`. Had a case where it overflowed, corrupted the heap and crashed WinUAE.

**Comment by tonioni** [comment]
Whats the best option? Do nothing (+log warning message?) if limit reached?

**Comment by BartmanAbyss** [comment]
Hmm.. dunno. maybe warn once + disable stackframes altogether. at this point there's probably some infinite loop going on anyway.

**Comment by tonioni** [comment]
Fixed in 4.10
