### ISSUE TITLE
P96: Conflict of DisplayID after latest changes

### ISSUE THREAD

**Issue by midwan** [tonioni/WinUAE#255]
After 5d5cb9f009a256e5488a54ded38a0b1438c9e5ff I noticed this error coming up in startup, when the P96 `uaegfx` driver is initialized:

![image](https://github.com/tonioni/WinUAE/assets/3877365/c6adcbf1-8846-4217-a953-1a4243de91fc)

Clicking on OK allows us to proceed, and after that the RTG system seems to work fine regardless.

Tested on WinUAE 5.0.0 and the latest P96 from IComp.
I see the same behavior in Amiberry after that commit was implemented there, as well.

**Comment by tonioni** [comment]
You probably have some ancient/obsolete/unsupported P96 config installed. Check uaegfx.info SETTINGSFILE parameter. If file exists, try removing it. You can also check if P96Prefs lists duplicate modes.

**Comment by midwan** [comment]
@tonioni 
No settings file is defined for this monitor driver:
![image](https://github.com/tonioni/WinUAE/assets/3877365/b75bacc7-b28c-44d9-876b-29f261d70bf3)

And I don't see any duplicate modes in P96Prefs either:
![image](https://github.com/tonioni/WinUAE/assets/3877365/de407734-1246-415f-ba31-bca280a6eef0)

![image](https://github.com/tonioni/WinUAE/assets/3877365/d39bc8c5-848e-43f2-ad64-95371c9ba64b)

**Comment by tonioni** [comment]
Probably need to check log next: which modes gets detected, perhaps there is something strange. No one else has reported this.

**Comment by midwan** [comment]
@tonioni 
Interestingly, I can only recreate this under one of my configs, but not the others. So there certainly is something special going on there, which I will investigate further.

Still, this only came up after the commit I mentioned above. Rolling back to an earlier version does not show the problem.

**Comment by tonioni** [comment]
Attach part of log that shows all detect modes from both configs. That patch is correct (confirmed by Picasso96 author that mode name should be same as mode prefix in preferences)

**Comment by midwan** [comment]
This is the relevant log extract from the setup that shows the error:
```
50-678 [175 011-134]: RTG mode mask: 212 BI=08134bcc
50-678 [175 011-134]: P96: Hardware sprite support enabled
50-678 [175 011-134]: uaegfx.card magic code: 00EF4800-00EF495A BI=08134BCC
50-678 [175 011-134]:  1: 50001000  320x 200 UAE: 320x 200
50-678 [175 011-134]:  2: 50011000  320x 240 UAE: 320x 240
50-678 [175 011-134]:  3: 50091000  320x 256 UAE: 320x 256
50-678 [175 011-134]:  4: 50021000  640x 400 UAE: 640x 400
50-678 [175 011-134]:  5: 50031000  640x 480 UAE: 640x 480
50-678 [175 011-134]:  6: 500A1000  640x 512 UAE: 640x 512
50-678 [175 011-134]:  7: 50831000  720x 480 UAE: 720x 480
50-678 [175 011-134]:  8: 50841000  720x 576 UAE: 720x 576
50-678 [175 011-134]:  9: 50041000  800x 600 UAE: 800x 600
50-678 [175 011-134]: 10: 50051000 1024x 768 UAE:1024x 768
50-678 [175 011-134]: 11: 50061000 1152x 864 UAE:1152x 864
50-678 [175 011-134]: P96: Non-unique mode 1176x664
50-678 [175 011-134]: 12: 50FF1000 1176x 664 UAE:1176x 664
50-678 [175 011-134]: 13: 508E1000 1280x 720 UAE:1280x 720
50-678 [175 011-134]: 14: 508F1000 1280x 768 UAE:1280x 768
50-678 [175 011-134]: 15: 50901000 1280x 800 UAE:1280x 800
50-678 [175 011-134]: 16: 50921000 1280x 960 UAE:1280x 960
50-678 [175 011-134]: 17: 50071000 1280x1024 UAE:1280x1024
50-678 [175 011-134]: 18: 50A11000 1360x 768 UAE:1360x 768
50-678 [175 011-134]: 19: 50931000 1366x 768 UAE:1366x 768
50-678 [175 011-134]: P96: Non-unique mode 1440x1080
50-678 [175 011-134]: 20: 50FE1000 1440x1080 UAE:1440x1080
50-678 [175 011-134]: 21: 50AA1000 1600x 900 UAE:1600x 900
50-678 [175 011-134]: P96: Non-unique mode 1600x1024
50-678 [175 011-134]: 22: 50FD1000 1600x1024 UAE:1600x1024
50-678 [175 011-134]: 23: 50961000 1600x1200 UAE:1600x1200
50-678 [175 011-134]: 24: 50971000 1680x1050 UAE:1680x1050
50-678 [175 011-134]: 25: 50981000 1920x1080 UAE:1920x1080
50-678 [175 011-134]: 26: 50991000 1920x1200 UAE:1920x1200
50-678 [175 011-134]: 27: 50A71000 1920x1440 UAE:1920x1440
50-678 [175 011-134]: 28: 50AF1000 2560x1440 UAE:2560x1440
50-678 [175 011-134]: P96: Non-unique mode 3413x1920
50-678 [175 011-134]: 29: 50FC1000 3413x1920 UAE:3413x1920
50-678 [175 011-134]: 30: 50B31000 3840x2160 UAE:3840x2160
50-678 [175 011-134]: SetSwitch() - amiga - immediate. Monitor=0
50-713 [177 010-059]: SetSwitch() - amiga - immediate. Monitor=0
```

And this is the relevant section from the config that doesn't show any errors for me:
```
13-171 [49 002-065]: RTG mode mask: 212 BI=400b2714
13-171 [49 002-065]: P96: Hardware sprite support enabled
13-171 [49 002-065]: uaegfx.card magic code: 00F04800-00F0495A BI=400B2714
13-171 [49 002-065]:  1: 50001000  320x 200 UAE: 320x 200
13-171 [49 002-065]:  2: 50011000  320x 240 UAE: 320x 240
13-171 [49 002-065]:  3: 50091000  320x 256 UAE: 320x 256
13-171 [49 002-065]:  4: 50021000  640x 400 UAE: 640x 400
13-171 [49 002-065]:  5: 50031000  640x 480 UAE: 640x 480
13-172 [49 002-065]:  6: 500A1000  640x 512 UAE: 640x 512
13-172 [49 002-065]:  7: 50831000  720x 480 UAE: 720x 480
13-172 [49 002-065]:  8: 50841000  720x 576 UAE: 720x 576
13-172 [49 002-065]:  9: 50041000  800x 600 UAE: 800x 600
13-172 [49 002-065]: 10: 50051000 1024x 768 UAE:1024x 768
13-172 [49 002-065]: 11: 50061000 1152x 864 UAE:1152x 864
13-172 [49 002-065]: P96: Non-unique mode 1176x664
13-172 [49 002-065]: 12: 50FF1000 1176x 664 UAE:1176x 664
13-172 [49 002-065]: 13: 508E1000 1280x 720 UAE:1280x 720
13-172 [49 002-065]: 14: 508F1000 1280x 768 UAE:1280x 768
13-172 [49 002-065]: 15: 50901000 1280x 800 UAE:1280x 800
13-172 [49 002-065]: 16: 50921000 1280x 960 UAE:1280x 960
13-172 [49 002-065]: 17: 50071000 1280x1024 UAE:1280x1024
13-172 [49 002-065]: 18: 50A11000 1360x 768 UAE:1360x 768
13-172 [49 002-065]: 19: 50931000 1366x 768 UAE:1366x 768
13-172 [49 002-065]: P96: Non-unique mode 1440x1080
13-172 [49 002-065]: 20: 50FE1000 1440x1080 UAE:1440x1080
13-172 [49 002-065]: 21: 50AA1000 1600x 900 UAE:1600x 900
13-172 [49 002-065]: P96: Non-unique mode 1600x1024
13-172 [49 002-065]: 22: 50FD1000 1600x1024 UAE:1600x1024
13-172 [49 002-065]: 23: 50961000 1600x1200 UAE:1600x1200
13-172 [49 002-065]: 24: 50971000 1680x1050 UAE:1680x1050
13-172 [49 002-065]: 25: 50981000 1920x1080 UAE:1920x1080
13-172 [49 002-065]: 26: 50991000 1920x1200 UAE:1920x1200
13-172 [49 002-065]: 27: 50A71000 1920x1440 UAE:1920x1440
13-172 [49 002-065]: 28: 50AF1000 2560x1440 UAE:2560x1440
13-915 [86 000-102]: RTG conversion: Depth=4 HostRGBF=9 
P96RGBF=9 Mode=4/4
13-916 [86 000-115]: SetSwitch() - Picasso96 800x600x32 (800x600x32) - immediate. Monitor=0
```

Full contents attached below

[winuae_debug_5.0.0_no_error.zip](https://github.com/tonioni/WinUAE/files/11775926/winuae_debug_5.0.0_no_error.zip)

[winuae_debug_5.0.0_with_error.zip](https://github.com/tonioni/WinUAE/files/11775927/winuae_debug_5.0.0_with_error.zip)

**Comment by tonioni** [comment]
Perhaps you still have customized Picasso96Settings in Devs:? (P96 uses this path by default).

**Comment by midwan** [comment]
@tonioni 
Confirmed, it was due to that file (DEVS:Picasso96Settings). If I rename it, the issue no longer comes up.

**Comment by tonioni** [comment]
I'd like to know where this file came from because it wasn't supposed to have any uaegfx resolution data. Picasso96Mode can't be used to create uaegfx modes so perhaps there was some other utility that someone experimented with it but noticed that nothing happened and thought nothing was written to the file. Invalid data was dormant there until recent P96/UAE versions.

**Comment by midwan** [comment]
The specific one came from the ZZ9000 installer. I can notify the author about it, but I'm not sure what the solution would be.
