### ISSUE TITLE
Qualifier mapping in the input mapper is broken in 5.1.0

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#268]
Test setup:
Windows 10
5.1.0 x64 build (portable version)

Clicking on "hotspots" in Qualifiers column in the input mapper does not bring up the Qualifier dialog.

Just checked and it was still working in 5.0.0, so this is a new regression in 5.1.0.

**Comment by tonioni** [comment]
Thanks, fixed. Some sub dialogs also missed high DPI support and dark mode support.

**Comment by johnnovak** [comment]
I appreciate you fixing these issues so quickly @tonioni. Great stuff!
