### ISSUE TITLE
Beneath a Steel Sky CD32 sound regression in 5.1.0

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#269]
In WinUAE 5.1.0, there are no voiceovers in the CD32 version of BASS. The dialog text just flashes very briefly, and there are just some popping sounds. Note the music works fine otherwise; the bug only affects the voiceovers when a character talks.

The voiceovers work flawlessly in 5.0.0 and 4.9.1, so this is a new regression in 5.1.0. In fact, I completed the game in 4.9.1 a while ago and there were zero issues.

I'm using "Beneath a Steel Sky (1994)(Virgin)(M4)[!]".

**Comment by tonioni** [comment]
Fixed, it was one 5.0 fix that changed too many things (68020 interrupt timing). It still works in 5.1 if cycle-exact is also ticked, fix that broke this game only affected non-ce modes.
