### ISSUE TITLE
"Create 256 color palette" screenshot ripper option is a bit buggy

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#270]
The new "create 256 color palette" option in the screenshot ripper is a bit buggy with certain AGA palettes at least.

I displayed this test IFF in DirOpus:
[Made_Nudge.zip](https://github.com/tonioni/WinUAE/files/13793817/Made_Nudge.zip)

This is what I see on my screen:

![image](https://github.com/tonioni/WinUAE/assets/698770/5852757d-0bf9-4a79-a217-54c28bcacb94)

And this is the resulting screenshot:
![bug](https://github.com/tonioni/WinUAE/assets/698770/e712897b-a347-4ead-aeb0-58488e178f28)

So certain colours got messed up, maybe some "wraparound" bug? You will only get the bug with certain input as it seems to be colour dependent, so make sure to test with this image. Same bug on 5.0.0 and 5.1.0.

If I uncheck the "create 256 color palette" option, the colors are fine.

**Comment by tonioni** [comment]
I can't duplicate. I loaded image in your attachment in Personal Paint (I won't use dopus, impossible to have exactly same versions of all libraries and other stuff..), hide the interface and took 256 color screen shot: screenshot was correct. Does other (much simpler) image viewers show same problem?

Also make sure "take screenshot before filtering" is ticked to get Amiga hardware level colors and image. (Shouldn't cause above problems even if enabled but usually it results in much more colors) Your attachment looks like it was already ticked because aspect ratio is different.

**Comment by johnnovak** [comment]
> Also make sure "take screenshot before filtering" is ticked to get Amiga hardware level colors and image.

Yes, I have both ticked.

![image](https://github.com/tonioni/WinUAE/assets/698770/ebe92be8-9a8a-4394-a9d9-5ce8b9080b56)

Okay, different AGA image and Deluxe Paint v5.2 this time. Disabling my CRT shader setup for the "what I see on my screen" screenshots taken outside of WinUAE to avoid confusion.

So these screenshots are taken outside of WinUAE, this is what I see on my screen:

![image](https://github.com/tonioni/WinUAE/assets/698770/558ee6de-d14d-414a-b941-96647ce81e0b)

![image](https://github.com/tonioni/WinUAE/assets/698770/285d0055-9871-41d2-9c8c-afe6c592a5b9)

And this is how the captured PNGs look like:

![image](https://github.com/tonioni/WinUAE/assets/698770/b50e4b42-7cbf-46db-a4a6-8ba95ed7dbca)

![image](https://github.com/tonioni/WinUAE/assets/698770/3426e2db-f3ee-4e09-933d-cee822b514e3)

Here are the unmodified captured PNGs:

[screenshots.zip](https://github.com/tonioni/WinUAE/files/13796643/screenshots.zip)

And here's the IFF file I'm using for the test:

[Made_AnimalReign.zip](https://github.com/tonioni/WinUAE/files/13796647/Made_AnimalReign.zip)

I'm just providing you image to make it easier to reproduce the issue. But I first noticed this when taking some image captures when playing Eye of the Beholder II AGA. If you still can't reproduce with DPaint AGA, I'm gonna give you a list of WHDLoad games that 100% manifest the problem.

I also tried your own FileMaster 2.2, but it doesn't support AGA 😄 

(Sidenote: This is a slightly different A1200 config, as you can see here I'm using "Double" line mode, and in my original ticket I was using "Single", hence the squashed aspect ratio of the captured images in my first report.)

**Comment by johnnovak** [comment]
And to state the obvious: I'm pressing the Save Screenshot button in the ripper to create the screenshots.

**Comment by tonioni** [comment]
Should be fixed now (5200b2), please confirm.

**Comment by johnnovak** [comment]
@tonioni I've tested it with a few dozens of AGA pics, and now it's perfect! Thanks! And palette index 0 is now left alone, which is a nice touch 👍🏻
