### ISSUE TITLE
Graphics artifacts when using the "TV" overscan modes

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#274]
There are graphics artifacts on the right edge of the screen when using any of the "TV" overscan modes. These dont' seem right, and they're gone in the "overscan" overscan modes.

To reproduce, just start Workbench and move the mouse pointer up and down. It's present in all games too that I tried.

![image](https://github.com/tonioni/WinUAE/assets/698770/5acb7b0b-121b-4015-ae9f-f1c832ab3473)

**Comment by tonioni** [comment]
Config file please, I can't duplicate with any usual configs. (It probably depends on CPU/chipset settings)

**Comment by johnnovak** [comment]
Sure thing @tonioni.

Stock A500 quickstart config + booting into WB 1.3 from floppy:

[Overscan test.zip](https://github.com/tonioni/WinUAE/files/13851766/Overscan.test.zip)

Result (look at the right side):

![image](https://github.com/tonioni/WinUAE/assets/698770/2effa701-a48d-426c-808b-eaa4e9dee1c0)

**Comment by tonioni** [comment]
Ah, it requires NTSC mode. Alternating line lengths are visible for some reason. Will be fixed.

**Comment by tonioni** [comment]
Fixed.
