### ISSUE TITLE
Feature: 2x scaling for the native on-screen display

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#278]
The native on-screen display is a great feature and I use it all the time. But it's quite small which is a problem for people with less-than-perfect eyesight, and a potential problem for everyone at higher screen resolutions than 1080p.

Would it be possible to add at least a 2x integer scaling option to the OSD? I've done a mockup, I think it would look nice.

The ideal solution would be to render it with a better font at a size that's somewhere between the current size and the 2x integer scaled size (or make it configurable), but a simple 2x integer scaling would be a nice quick win.

## Current at 1080p

![image](https://github.com/tonioni/WinUAE/assets/698770/fe02a39d-4dca-468e-bec2-d43f6b6d60e1)

## Mockup of OSD with 2x scaling at 1080p

![image](https://github.com/tonioni/WinUAE/assets/698770/c91a56a1-a19b-43dd-b40d-0a7733126b99)

**Comment by tonioni** [comment]
Scaling was already possible by undocumented config file entry (show_leds_size and show_leds_size_rtg, parameter is decimal multiplier) but latest beta now has also OSD font type/size selection (misc panel) which hopefully is much more useful.

**Comment by johnnovak** [comment]
> Scaling was already possible by undocumented config file entry (show_leds_size and show_leds_size_rtg, parameter is decimal multiplier) but latest beta now has also OSD font type/size selection (misc panel) which hopefully is much more useful.

That's great, trying it today! 🚀

**Comment by johnnovak** [comment]
It works splendidly @tonioni, great addition! It even handles very large fonts correctly as shown on the below screenshot, great!

I noticed I can only change the OSD font in "windowed" mode. In "fullscreen" and "full-windowed" modes, changing the OSD font doesn't have any effect. Is this intentional?

![image](https://github.com/tonioni/WinUAE/assets/698770/e1a0b696-7805-4674-bf53-cf7a039c81da)

**Comment by tonioni** [comment]
No. Changing OSD font while in full-window or fullscreen mode saved the config incorrectly, making it no-op. Fixed.

**Comment by johnnovak** [comment]
Confirming the fix works; now I can change the OSD font in full-window and fullscreen mode too. Thanks! 👍🏻 

The OSD now works perfectly, but I noticed a small glitch with the floppy insertion message. As you can see, the top of the letters is cut off:

![image](https://github.com/tonioni/WinUAE/assets/698770/2850364a-c178-497f-a74d-2e0d4b626c59)

That's with Lucida Console, Regular, size 10.

![image](https://github.com/tonioni/WinUAE/assets/698770/aaa6a47d-0d20-467c-8733-2c409d59473e)

Ok, let's see how it behaves with a much larger font, let's check out size 16:

![image](https://github.com/tonioni/WinUAE/assets/698770/9f1bba92-1ad5-4507-9172-276f60cc76c2)

Now the floppy message is perfect... but the OSD is misaligned and being clipped. Forcing a refresh/redraw by switching to full-windowed then back to windowed fixes it:

![image](https://github.com/tonioni/WinUAE/assets/698770/e5c9e949-7f01-482a-bc76-83b02494c49f)

---

So, two remaining issues:

- Floppy insertion messages are being clipped at the top at certain font sizes (this is unfixable).
- The OSD gets misaligned when changing to larger font sizes at runtime (forcing a full redraw or an emulator restart fixes it).
-

**Comment by johnnovak** [comment]
All visual glitches when changing the font size are fixed in 5.2.0 b7, thanks @tonioni.
