### ISSUE TITLE
Alignment problem when switching between Single & Double line modes via filter presets

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#280]
Use the attached config:
[winuae.zip](https://github.com/tonioni/WinUAE/files/13884488/winuae.zip)

But what you really need to reproduce it is the below two filter presets:

```
[FilterPresets]
Laced PAL 3.0x=0,0,4000.000000,1000.000000,1.000000,1.000000,0.000000,0.000000,0,0,17,1,0,0,2,2,0,0,0,0,0,0,0,0,0,1,0,0,-1,0,-1,0
PAL 3.0x=0,0,1000.000000,1000.000000,1.000000,1.000000,0.000000,0.000000,0,0,17,1,1,1,2,2,0,0,0,0,0,0,0,0,0,1,0,0,-1,0,-1,0
```

### Repro steps

1. Start WinUAE and set a basic A500 config. We'll reproduce the bug at the boot screen 😎 

2. F12, go to **Hosts / Filters**, select the **PAL 3.0x** preset, then press Load and OK. The output should look like this:

![image](https://github.com/tonioni/WinUAE/assets/698770/30453062-0f5f-45d6-8bd6-29153fbec99b)

3. So far so good. Now load the **Laced PAL 3.0x** preset. Oops!

![image](https://github.com/tonioni/WinUAE/assets/698770/1a360dc2-c33b-4962-b4b8-9584165373b9)

4. Resizing the window, or switching to fullscreen/full-windowed fixes it as it forces a refresh. 

5. Let's do it in the other direction! Load **PAL 3.0x** again. Result:

![image](https://github.com/tonioni/WinUAE/assets/698770/07950284-9e27-41c3-b919-a11a5137b745)

**Comment by tonioni** [comment]
Partially fixed. Immediately after loading the profile, display won't still be fully updated but it will automatically reset after exiting the GUI.

**Comment by johnnovak** [comment]
Confirming it works now like you've described. I think that's an acceptable solution.

**Comment by johnnovak** [comment]
Closing as I think the current solution is fine.
