### ISSUE TITLE
Savestate UI path does not get updated in one very specific edge case

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#283]
I really hope you're not completely sick of my reports yet @tonioni, but I keep running into weird edge cases. I'm not intentionally hunting for these, I swear! 😅 

I've spent quite a bit of time to narrow this one down and provide a repro pack as it was confusing as hell initially.

The important thing (and the good news) is that this is _purely_ a UI issue -- but a confusing one.

---

1. Download my repro pack, unpack it to an empty folder, then copy the WinUAE 5.2.0 b4 executable into that folder.
    Repro pack: [savestate-ui-path-test.zip](https://github.com/tonioni/WinUAE/files/13935041/savestate-ui-path-test.zip)

3. Start WinUAE, load the "Foo" config, then click Start. The config is set up to load a savestate `.\Games\Foo\Savestates\Start.uss`. 

4. F12 then check the savestate path. So far so good. Don't close the UI yet!

    ![image](https://github.com/tonioni/WinUAE/assets/698770/5a76e1dc-586a-4d53-ae76-02a9da3c3971)

5. Now while staying in the UI, load the "Bar" config but don't hit Start yet! This config is set up to load a savestate too, called `.\Games\Bar\Savestates\Start.uss`. Now check the savestate path again; it's still the savetate path from the _previous_ "Foo" config!
    
    ![image](https://github.com/tonioni/WinUAE/assets/698770/4a8bc540-a2ac-4298-a824-bcb6044a2fc3)

6. Click Start, then F12, and check the savestate path again. Starting the config has updated the path in the UI.

    ![image](https://github.com/tonioni/WinUAE/assets/698770/a957dbd3-1687-4ba4-91cf-eac6d140cfb4)

---

So this is a purely UI update issue, but it can be confusing when you load configs with "embedded" savestates that the savestate path "lags one step behind".

**Important:** the problem is **only** reproducible if the two savestates have the **same** filename! The paths can of course be different. If the filenames are different (e.g., `FooStart.uss`, and `BarStart.uss`), then the problem does NOT happen.

Still, I use "standard" savestate names for the different games for certain features I'm providing, stored inside the individual game folders (e.g., `SkipCodeCheck.uss`, `SkipIntro.uss`), so this very much affects my setup.

**Comment by tonioni** [comment]
These are fixed (+paths in ini/registry are now always correctly relative or absolute) in usual winuae.7z. 

I am not going to get annoyed, your report are valid and very good reports, easy to duplicate but bugs that most "normal" users never notice.

**Comment by johnnovak** [comment]
Confirming the bug is fixed in 5.2.0 beta 7. Nice job @tonioni, and thanks for bearing with my obscure bug reports 🎉
