### ISSUE TITLE
Picmatic Marbella Vice rom doesn't continue loading and service menu key doesn't work

### ISSUE THREAD

**Issue by gustavoalara** [tonioni/WinUAE#288]
Following a long wait, the Marbella Vice laserdisc has finally been dumped; however, the ROM freezes and constantly restarts without loading the video (using the default WinUAE settings).. I've tried to access the service menu but the assigned key doesn't work neither

**Comment by gustavoalara** [comment]
With the last WinUAE 5.2.0 Beta 7 the rom continues loading and it's possible to insert coins, start the game and shoot, but it looks like the video is not used correctly by the rom

https://github.com/tonioni/WinUAE/assets/7902641/86c595c9-07e0-4d9b-be5a-8096c0b2ffe5

**Comment by gustavoalara** [comment]
Its possible to access service menu now, but is impossible to play yet

![image](https://github.com/tonioni/WinUAE/assets/7902641/22e65b36-3e4b-4a2e-acbd-7892d4470b15)

**Comment by tonioni** [comment]
I haven't test it (too lazy to convert the video) but game only sends absolute frame positions to LD player, not much can go wrong there.

Problem probably is the video and the way winuae plays (uses obsolete video grab method) which requires both codec and video format that can seek to any frame position freely. Don't ask me, I have zero interest in video files and formats :)

**Comment by tonioni** [comment]
It uses old DirectShow API, which uses Windows codecs, nothing is built-in (but as I said above, not all codecs support frame-perfect positioning) and some codec packs have buggy codecs.

But playback not working in Marbella Vice was missing LD player command (and some timing problems), see last few posts here: https://eab.abime.net/showthread.php?p=1668052

**Comment by gustavoalara** [comment]
Thanks a lot @tonioni 

With this new version, the intro video, the one displayed when the credits are rolled, works, and even when pressing start, it seems that the game starts correctly. However, in-game, it seems that the shooting does not work. Interestingly, in the minigame shown after the first death, the gun works, and you can shoot at the targets (this can be seen at the 2:00 minute mark of the YouTube video I uploaded).

this is the url of the youtube video I made:

https://www.youtube.com/watch?v=N_aMcyv-JmI

Thank you very much for your efforts. I'm Spanish, and this game is a classic that we've been eagerly waiting to play for a long time since all the arcades disappeared.

**Comment by gustavoalara** [comment]
I close the issue as Toni is working on it and the advances are very promising
