### ISSUE TITLE
WHDload.prefs disabled JIT issues.

### ISSUE THREAD

**Issue by RWXecute** [tonioni/WinUAE#289]
Having problems when WHDLoad is configured to disable JIT on start. Sounds effects are missing from IK+, Chaos Engine fails to start. JIT on and they both work. Just switching JIT on and off enables and disables sound effects.

**Comment by tonioni** [comment]
5.1.0? It has interrupt related bug that affects 68020+ non-JIT modes and breaks some (mainly badly coded) games. Already fixed in 5.2 betas (final will be out in 1-2 weeks or so)

**Comment by RWXecute** [comment]
Yes. 5.1.0. I just tried the 5.2 beta and it's all good, thanks.
