### ISSUE TITLE
Possible overscan regression

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#291]
Not sure if this change in behaviour is more or less accurate or intentional, but I thought it's best if I report it.

**5.2.0 beta 7**
A500, Kick 1.3, NTSC, OCS, Overscan mode
The bottom scanline in the Workbench screen is incomplete and the last few pixels are flickering.

If I switch to ECS Agnus, there's one less scanline, so the glitch is hidden. The flickering in particular is slightly annoying.

**5.2.0 beta 4**
Same config, with OCS the extra scanline is shown in Overscan mode, but it's a _complete line_ and there is no flicker.

---

This is how the incomplete last scanline looks like in beta 7 with NTSC + OSC + Overscan:

![overscan-5 2 0-b7](https://github.com/tonioni/WinUAE/assets/698770/c827d9c0-ea37-40b5-888d-2a40b52b910b)

**Comment by johnnovak** [comment]
You should be able to reproduce it with this config right at the boot screen:
[Overscan Test.zip](https://github.com/tonioni/WinUAE/files/14232094/Overscan.Test.zip)

The config has OSC + NTSC, but I found another bug when you switch to PAL (see screenshots below; in PAL mode theres a glitch at the end of the top row).

As mentioned, switching to any other chipset than OCS "fixes" it.

### OCS / NTSC

![image](https://github.com/tonioni/WinUAE/assets/698770/b361ae7b-4df7-4f6e-baf1-fd03b019c1ae)

### OCS / PAL

![image](https://github.com/tonioni/WinUAE/assets/698770/6a2a62c8-3479-4590-9469-e3584513bd76)

**Comment by johnnovak** [comment]
Just tested this with beta 8, but the issue is still there using repro pack from the above post. It's exactly the same behaviour, no improvement.

**Comment by johnnovak** [comment]
Yeah, it's pretty annoying when watching PAL OCS demos. Can you please fix @tonioni ?

Config & disk image attached.

[Megademo (Alcatraz, 1988).zip](https://github.com/tonioni/WinUAE/files/14237240/Megademo.Alcatraz.1988.zip)
[Alcatraz-Megademo2.zip](https://github.com/tonioni/WinUAE/files/14237236/Alcatraz-Megademo2.zip)

![image](https://github.com/tonioni/WinUAE/assets/698770/a8e059d5-2b27-432f-a716-8d8f94a1afe3)

**Comment by tonioni** [comment]
Blank lines on top and bottom right: these are now disabled unless overscan mode is overscan+ or higher. (These blank lines are not emulation bug, they really do happen with OCS Denise and are visible on most normal displays as long as it shows full overscan. And they do flicker if NTSC because NTSC line length alternates)

Demo: I can only see short blue line in bottom right corner which is correct behavior. I can't duplicate long blue line except by enabling Overscan+ mode which shows all visible lines (same as real A500 + OSSC can show when OSSC is configured to show everything possible). Do you have any centering options enabled? If yes, does it happen without it? (I guess I'll need to completely disable last possible visible line unless overscan+ because almost no normal display device can show it)

**Comment by johnnovak** [comment]
Yes, the long blue line only shows with vertical centering enabled. If that's disablef, I only get a very short blue line in the bottom right corner.

IMO it's fine to chop off a few more lines to make sure none of the flickering and incomplete line artifacts show up with any setting combinations in normal Overscan mode. It's not as if there was a strict standard on the exact overscan size in monitors/TVs, and you adjusted the horiz/vert stretch controls on monitors anyway until things looked good. No one would have adjusted it so to see visible flicker.

**Comment by johnnovak** [comment]
Most things work as expected with beta 9, no weird flickering extra lines anymore.

The Alcatraz Megademo is still affected but probably it's a weird outliner, so no big deal. I'll raise this again if I come across more weirdness with Overscan, but probably we can close the issue ticket for now.

**Comment by tonioni** [comment]
I added one more overscan/overscan+ difference: do not show last almost always hidden line if not overscan+ or larger. This is basically same behavior as pre-4.9 which didn't have any support for line "wrap around" (where bottom last line is actually line 0 or 1 depending on config, or even larger if programmed mode)

**Comment by johnnovak** [comment]
Alcatraz Megademo is now fine even with vertical centering (the full-length bright line at the bottom of the screen is gone).

I could not trigger the weird incomplete flickering first/last line either in PAL or NTSC.

Great job @tonioni 🎉
