### ISSUE TITLE
Feature request: new "Always off (LED only)" filter option

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#293]
Currently, the "Always off" filter option disables _both_ audio filters:

- the 6 dB/oct RC filter at 5 kHz (fixed filter)
- and the 12 dB/oct Butterworth filter at 3.2 kHz (soft-switchable LED filter)

One more option called "Always off (LED only)" would be very welcome--this would be the "inverse" of the current "Always on" option. It would leave the fixed filter on and always force-disable the LED filter (but only the LED filter).

Then the current "Always off" option could be renamed to "Always off (both filters)" or something.

I personally would like to use "Always off (LED only)" in some games and demos that turn the LED filter on via software, but I practically never want to disable _both_ filters which sounds exceedingly ugly and harsh because of the extreme aliasing (however, that's useful for raw captures intended for further post-processing, just not really for regular emulator use for "enjoyment").

**Comment by tonioni** [comment]
Something like you suggested is now implemented. (New option added to sound filter panel). I prefer "Always on (Fixed only)". Always off when something is still on sounds wrong, also A1200/A4000 does not have fixed filter. It only has led filter.

**Comment by johnnovak** [comment]
> Something like you suggested is now implemented. (New option added to sound filter panel). I prefer "Always on (Fixed only)". Always off when something is still on sounds wrong, also A1200/A4000 does not have fixed filter. It only has led filter.

Thanks @tonioni. Yeah I prefer A500 with the fixed filter only too. I'm not too fond of the A1200/A4000 sound with no fixed filter.
