### ISSUE TITLE
Overlapping text in about dialog

### ISSUE THREAD

**Issue by johnnovak** [tonioni/WinUAE#294]
Very minor issue, and it doesn't bother me at all. But I guess it's trivial to fix, so I'm reporting it.

This is with the defaults on Windows 10, 1080p screen, 100% DPI scaling.

![image](https://github.com/tonioni/WinUAE/assets/698770/a230a5ee-3100-4366-866e-2ed7f555c738)

**Comment by tonioni** [comment]
This should have been fixed in final 5.2.0
