### ISSUE TITLE
Reading color register strips out the highest bit (bit 15)

### ISSUE THREAD

**Issue by piru** [tonioni/WinUAE#297]
Reading color registers on real amiga returns the value anded with 0x8fff. So bit 15 is also preserved. Bits 12, 13, 14 are read back as zero though.

Test program that writes 0xffff to color0 and reads back 0x8fff (tested on A1200):
```
_LVODisable	EQU	-120
_LVOEnable	EQU	-126

dmaconr		EQU	$002
dmacon		EQU	$096
bplcon2		EQU	$104
color0		EQU	$180

main:
	lea	$dff000,a5

	move.l	(4).w,a6
	jsr 	(_LVODisable,a6)

	move.w	(dmaconr,a5),_dmacon
	move.w	#$7fff,(dmacon,a5)

	move.w	#0,(bplcon2,a5)
	move.w	#$ffff,(color0,a5)
	move.w	#1<<8,(bplcon2,a5)	; set RDRAM
	moveq	#0,d7
	move.w	(color0,a5),d7

	move.w	#0,(bplcon2,a5)

	move.w	(_dmacon,pc),d0
	or.w	#$8000,d0
	move.w	d0,(dmacon,a5)

	jsr	(_LVOEnable,a6)

	move.l	d7,d0
	rts

_dmacon: ds.w 1
```

**Comment by tonioni** [comment]
Fixed. For some reason color register genlock transparency bit handling was broken, probably happened long time ago. (I did validate it against real A1200 years and years ago)
