### ISSUE TITLE
Tierras Salvajes Support

### ISSUE THREAD

**Issue by gustavoalara** [tonioni/WinUAE#303]
Hi @tonioni 

The last Picmatic game video (Tierras Salvajes) has been released recently. 
As the rom is on the MAME romset from time ago. Is possible to add it to the list of supported games?

Thanks in advanced!

**Comment by faluki1983** [comment]
I join the request

**Comment by poskass** [comment]
Me too

**Comment by Armandokevin** [comment]
One more here who joins the question

**Comment by tonioni** [comment]
Was already done about 2 days ago (with some fixes yesterday).

https://eab.abime.net/showthread.php?t=84888 (first and last posts for details)
