### ISSUE TITLE
Bad atomic write?

### ISSUE THREAD

**Issue by jacereda** [tonioni/WinUAE#309]
Looking at this:

https://github.com/tonioni/WinUAE/blob/c9af906a1c6817636e2a8cd1bc7e06cb21e73467/traps.cpp#L705

`outtrap_alloc` contains `RTAREA_TRAP_DATA_SEND_NUM` (1) entries.
The code is indexing at `RTAREA_TRAP_DATA_NUM`  (4), so it should be past the end of the array.

**Comment by tonioni** [comment]
I don't remember much how this mess worked (only way I found to have working UAE expansion in OS4) but this code seems to be unused. It seems to be only called from bsdsocket emulation which can't be OS4 compatible. (It has built-in TCP/IP stack that can't be replaced)

Yes, it has out of bounds access but I am not even sure what it was supposed to do :)
