### ISSUE TITLE
Concatenating mismatched strings (expansion.cpp)

### ISSUE THREAD

**Issue by lab313ru** [tonioni/WinUAE#62]
When compiling with Visual Studio, I'm getting an error C2308 here (line 2568):
{   // 16 - 18
    _T("Memory\0""1M\0""2M\0""4M\0""8M\0""16M\0""32M\0"),
    _T("memory\0""1M\0""2M\0""4M\0""8M\0""16M\0""32M\0"),
    true, false, 0
},

Maybe it will be better to refactor these lines with getting every part of string in _T() macros like this?
    _T("Memory\0") _T("1M\0") _T("2M\0") _T("4M\0") _T("8M\0") _T("16M\0") _T("32M\0"),
    _T("memory\0") _T("1M\0") _T("2M\0") _T("4M\0") _T("8M\0") _T("16M\0") _T("32M\0"),

**Comment by tonioni** [comment]
Visual Studio 2015 compiles it fine but I can change it, at least makes it less confusing :)

**Comment by timofonic** [comment]
Did you change it? What happened? What's the status of this?
