### ISSUE TITLE
blitter.cpp - do_blitter2()

### ISSUE THREAD

**Issue by PandTomB** [tonioni/WinUAE#99]
I think the line
	blit_firstline_cycles = blit_first_cycle + (blit_diag[0] * blt_info.hblitsize + cpu_cycles) * CYCLE_UNIT;
should be replaced by
	blit_firstline_cycles = blit_first_cycle + (blit_diag[0] * blt_info.hblitsize) * CYCLE_UNIT + cpu_cycles;
because cpu_cycles are already scaled by CYCLE_UNIT.

**Comment by tonioni** [comment]
Correct, thanks. It is so rarely used hack in non-cycle exact modes that it never caused any noticeable side-effects.
